name: CI Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_DB: teste
        ports:
          - 5432:5432

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, bcmath, pdo_mysql

      - name: Composer install
        run: |
          cd backend
          composer install

      - name: Rodar testes Laravel
        run: |
          cd backend
          php artisan test